[mongodb]
mongodb.rachanadev.online
[catalogue]
catalogue.rachanadev.online
[redis]
redis.rachanadev.online
[user]
user.rachanadev.online
[cart]
cart.rachanadev.online
[frontend]
frontend.rachanadev.online
[mysql]
mysql.rachanadev.online
[shipping]
shipping.rachanadev.online
[rabbitmq]
rabbitmq.rachanadev.online
[payment]
payment.rachanadev.online

[all.vars]
ansible_user=ec2-user
ansible_password=DevOps321
# i gave the variables for all hosts here.


